### PR TITLE
Feat/update movement service

### PR DESCRIPTION
**Pull request by N3moAhead**
## Bug Fixes

- Fixed a bug that caused people to jump back and forth on their position when they reached their destination and wanted to stay there.

## Features
- Added a feature where people now always stay at home and at work for a currently set 50 ticks. Before they go back home or to work.

### CODE REVIEW

**Review by InaasHammoush — COMMENTED** [review]
looks good from my side but I noticed that there are people just standing in the street and not moving at all. Is there a reason for that or is it a bug?

**Review by joewilliams007 — APPROVED** [review]
Looks good! I also tested it and it seems to work very well.

**Comment by N3moAhead** [comment]
> looks good from my side but I noticed that there are people just standing in the street and not moving at all. Is there a reason for that or is it a bug?

Yes your totally right! Thats a bug that i introduced. But i fixed it in this PR #26 👍🏻

**Comment by N3moAhead** [comment]
@InaasHammoush I just cherry-picked the fix. So it does work now 👍🏻  Thanks for pointing that out 🙏🏻

**Pull request merged**
