### PR TITLE
40 set the age when creating humans

### LINKED ISSUE #40: Set the Age when creating humans
At the moment, people are created without being assigned an age in the Constructor.

Each person needs an age depending on the ratio between old, adult and young people set in the configuration.

An age should be assigned to each person when they are created.

### LINKED ISSUE #43: Duplicate method.
In the SimulationController the `updateSimulation(tick);` method is called twice in a row.

### PR DESCRIPTION
**Pull request by ColorfulBisuketto**

### CODE REVIEW

**Comment by ColorfulBisuketto** [comment]
Forgot a quick bug.

**Review by joewilliams007 — COMMENTED** [review]
Heyy, i dont quite understand the reason for using that many for and while loops

Why not just iterate over humans and address Age.Child and Age.Elderely, until these are at their max.

(if random placement is needed it could randomly either add Elderly/Child and then increase the counter for each till they are at max)

And also i would think in the current state the elderly while loop, could catch some just added children randomly and overwrite their value, as human.getAge() also wont be Age.Adult in that case. Or is that intentionally?

**Comment by ColorfulBisuketto** [comment]
Thanks for the feedback!

Yes, many of the loops are unnecessary. Seems like I just stopped thinking there...

And regarding overwriting children, now that I take a look again I'm surprised the simulation even runs and doesn't get into an infinite loop ... I planned to use != in the while part to make sure only Adults were overwritten but my mind must've went to "only assign a different value if Adult" and gotten them mixed up.

Anyways I'll see to it, that I fix my stuff before pestering everyone again.

**Comment by joewilliams007** [comment]
> Thanks for the feedback!
> 
> Yes, many of the loops are unnecessary. Seems like I just stopped thinking there...
> 
> And regarding overwriting children, now that I take a look again I'm surprised the simulation even runs and doesn't get into an infinite loop ... I planned to use != in the while part to make sure only Adults were overwritten but my mind must've went to "only assign a different value if Adult" and gotten them mixed up.
> 
> Anyways I'll see to it, that I fix my stuff before pestering everyone again.

No problem at all! This is exactly what the reviews are for, to get right on track with the feedback again. Don't stress yourself too much.

**Comment by ColorfulBisuketto** [comment]
Assignment now uses one loop and one stream, at the cost of some complexity (I hope the comments explain what is going on well enough)
The possible infinite loop should also be gone.

**Review by joewilliams007 — APPROVED** [review]
++ Thanks for fixing it. It looks okay now. Still a bit complex and confusing to read a solution but at least much more efficient than before :).

As we are quite near the end we cant spend too much on code quality sadly. But given it works its good for this project now!

**Pull request merged**
