### PR TITLE
Feat/sketching initial ideas

### PR DESCRIPTION
**Pull request by N3moAhead**
I have just started to sketch out some of my ideas for the architecture. Im no Java Export so it would be very nice to hear your thoughts on my current idea. Feel free to change what you want to change, this pull request should just help us think about the architecture we want.

### CODE REVIEW

**Comment by joewilliams007** [comment]
Can we please decide on whether we want to use this structure as a base and merge it into the main branch ASAP, so that we can start building the UI as well as the back end in separate branches with this structure.

**Comment by N3moAhead** [comment]
Yes, let's go ahead with that! I haven't heard any objections, so I think we can start with this structure. If we have any concerns along the way, we can always make adjustments. 👍🏻

**Comment by N3moAhead** [comment]
I just can't approve it myself. You are welcome to approve and merge it 👍🏻

**Review by joewilliams007 — APPROVED** [review]
The structure looks good so far. Small changes may need to be done during further development.

**Pull request merged**
