### PR TITLE
Changes to make BioCollapse testable

### PR DESCRIPTION
**Pull request by N3moAhead**

### CODE REVIEW

**Comment by ColorfulBisuketto** [comment]
Looks amazing!
I'll test as soon as I get home.

Think it would be good if everyone could take a quick look if it seem good for them as well.

**Review by Driemtax — APPROVED** [review]
Looks good from my side! I hope i didnt miss anything i rather skimmed trough it

**Review by ColorfulBisuketto — APPROVED** [review]
Tested it and it seems to work.

**Review by InaasHammoush — APPROVED** [review]
I also tested it and it seems to work well. Thank you for your updates.

**Comment by N3moAhead** [comment]
Thanks for the Reviews and the kind feedback 🙏🏻

**Pull request merged**
