### PR TITLE
Updated the way infections work 

### LINKED ISSUE #48: Simulation too fast complete when mortality > 0
When the mortality rate is higher than 0, the simulation ends very fast, even when increasing "good" parameters

### PR DESCRIPTION
**Pull request by N3moAhead**
- During the incubation time the human is infected but not contagious
- After the incubation time the infection time starts. The human is contagious.
- After the infection time ends the probabilty to die gets called once.

### CODE REVIEW

**Comment by N3moAhead** [comment]
grafik

Im getting more interesting results now 👍🏻

**Review by joewilliams007 — APPROVED** [review]
Love these changes!!! The code looks very clean. Can't wait to test it later.

**Comment by joewilliams007** [comment]
@N3moAhead during testing, i cant replicate graphs that u have. for me it is very linear. How did you set your config? EDIT: i did manage to get a few nice graphs :). We gotta have a feeling for the config

**Comment by N3moAhead** [comment]
@joewilliams007 yeah the default settings really dont work well haha we will have to change them XP

**Comment by joewilliams007** [comment]
@N3moAhead yes. For the demo maybe we should have two examples. One that is the default and one in which we make "live" changes to the config that we have noted down. Idk?

**Pull request merged**
