### PR TITLE
Hooked main loop to display of map. Added a display of the current FP…

### PR DESCRIPTION
**Pull request by joewilliams007**
The main simulation loop is now connected to the font end. Added the display of the current FPS.

### CODE REVIEW

**Review by N3moAhead — COMMENTED** [review]
Hey the code is looking great! Its amazing to see the front and backend to finally join together 👍🏻 

I also tested it and it seems to work 👍🏻  With that we would be finally able to test our Services better.

The only thing that i found is, that this Error shows on the console:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "this.humanData" is null
        at src.com.biocollapse.view.MapPanel.drawHumans(MapPanel.java:147)
        at src.com.biocollapse.view.MapPanel.paintComponent(MapPanel.java:135)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
        at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5318)
        at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:255)
        at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1336)
        at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5266)
        at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5076)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:878)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:861)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:861)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:834)
        at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
        at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1897)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
       
       
       Do you know if we will have to do something about it @joewilliams007?

**Comment by N3moAhead** [comment]
I just added a small Nullcheck and now the error does not appear on the console anymore 👍🏻

**Comment by N3moAhead** [comment]
The rest of the code works as intended and i will merge it in a second 👍🏻

**Review by N3moAhead — APPROVED** [review]
The Code looks very good to me and i also tested it and it works! Thanks for the changes @joewilliams007 🙏🏻

**Comment by joewilliams007** [comment]
@N3moAhead alright. Thanks for merging! The error probably suggests that the humans arent initialised in the first iteration or sth similar. A null check resolves it for now, not the cleanest solution, but i will take it 🥲. A null check is good in any way.

**Pull request merged**
